property.path=test-results/logs-results

# File appender
appender.file.type=File
appender.file.name=FileAppender
appender.file.fileName=${path}/log_${date:dd-MM-yyyy_HH-mm-ss}.log
appender.file.layout.type=PatternLayout
appender.file.layout.Pattern=[%p] - [%d{dd-MM-yyyy HH:mm:ss}] [%t] [%c:%L] - %m%n
appender.file.filter.threshold.type=ThresholdFilter
appender.file.filter.threshold.level=debug
appender.file.layout.disableAnsi=false

# %p= the log level, %d for the date or time , %t for thread name, %c:%L for className and line, %m for message,%n for new line

# Console appender
appender.console.type=Console
appender.console.name=ConsoleAppender
appender.console.layout.type=PatternLayout
appender.console.layout.Pattern=[%p] - [%d{dd-MM-yyyy HH:mm:ss}] [%t] [%c:%L] - %m%n
appender.console.filter.threshold.type=ThresholdFilter
appender.console.filter.threshold.level=debug
appender.console.layout.disableAnsi=false

# Root logger option
rootLogger=debug, FileAppender, ConsoleAppender
rootLogger.level=debug